services:
  postgres:
    image: postgres:16
    container_name: dbflow-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - dbflow_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: dbflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    command: ["sh", "-c", "redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0 --protected-mode no --notify-keyspace-events Ex"]
    restart: always

volumes:
  dbflow_postgres_data:
  redis-data: